#!/usr/bin/env python
""" generated source for module Token """
# package: com.stuffwithstuff.bantam
# /**
#  * A simple token class. These are generated by Lexer and consumed by Parser.
#  */
class Token(object):
    """ generated source for class Token """
    def __init__(self, type, text):
        """ generated source for method __init__ """
        mType = type
        mText = text

    def getType(self):
        """ generated source for method getType """
        return mType

    def getText(self):
        """ generated source for method getText """
        return mText

    def __str__(self):
        """ generated source for method toString """
        return mText

    mType = None
    mText = None

